"""empty message

Revision ID: 0c89fd2c1314
Revises: 28120ffeae8a
Create Date: 2020-02-26 17:02:20.188100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c89fd2c1314'
down_revision = '28120ffeae8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ha_repair_item', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute("UPDATE ha_repair_item SET completed=false")
    op.alter_column('ha_repair_item', 'completed', nullable=False)
    op.add_column('ha_repair_item', sa.Column('completed_at', sa.Date(), nullable=True))
    op.add_column('ha_repair_item', sa.Column('created_at', sa.Date(), nullable=True))
    op.drop_column('ha_repair_item', 'repair_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ha_repair_item', sa.Column('repair_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('ha_repair_item', 'created_at')
    op.drop_column('ha_repair_item', 'completed_at')
    op.drop_column('ha_repair_item', 'completed')
    # ### end Alembic commands ###
