"""empty message

Revision ID: 4a1cfdc8498a
Revises: 3747d239432d
Create Date: 2020-01-03 17:39:45.792062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1cfdc8498a'
down_revision = '3747d239432d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(length=10), nullable=True),
    sa.Column('housing_association_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['housing_association_id'], ['housing_association.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_number', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartment')
    op.drop_table('building')
    # ### end Alembic commands ###
