"""empty message

Revision ID: da1f75c64ed1
Revises: c951a181154d
Create Date: 2019-12-29 12:28:51.243936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1f75c64ed1'
down_revision = 'c951a181154d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housing_association', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housing_association', 'created')
    # ### end Alembic commands ###
