"""empty message

Revision ID: fcd3f086662c
Revises: e9162447d8c8
Create Date: 2020-02-18 19:01:03.171522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd3f086662c'
down_revision = 'e9162447d8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ha_repair_item', sa.Column('title', sa.String(length=255), nullable=True))
    op.execute("UPDATE ha_repair_item SET title = 'none'")
    op.alter_column('ha_repair_item', 'title', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ha_repair_item', 'title')
    # ### end Alembic commands ###
